[package]
name = "neo-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
neo-base   = { path = "../neo-base", default-features = false, features = ["std"] }
bytes      = "1.5"
tokio-util = { version = "0.7", features = ["codec"] }
futures    = "0.3"
thiserror  = "1.0"
uuid       = { version = "1", features = ["v4"] }
serde      = { version = "1", features = ["derive"], optional = true }
tracing    = "0.1"
rand       = "0.8"
lz4_flex   = "0.11"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[features]
default = []

[workspace]
