[package]
name = "neo-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "5.5"
futures = { version = "0.3", default-features = false, features = ["alloc", "std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
