[package]
name = "neo-core"
version = "0.1.0"
edition = "2024"

[dependencies]
neo-base   = { path = "../neo-base", default-features = false }
neo-crypto = { path = "../neo-crypto", default-features = false }

hashbrown = { version = "0.16" }
thiserror = { version = "2", default-features = false }
bytes     = { version = "1.10", default-features = false }

serde      = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

hex = { version = "0.4", default-features = false, features = ["alloc"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }

[features]
default = []

std = [
    "neo-base/std",
    "neo-crypto/std",
    "thiserror/std",
    "bytes/std",
]

enclave = [
    "neo-base/enclave",
    "neo-crypto/enclave"
]
