[package]
name = "neo-store"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
dashmap   = "5.5"
parking_lot = "0.12"
neo-base  = { path = "../neo-base", default-features = false, features = ["std", "derive"] }
serde = { version = "1", features = ["derive"] }
sled = { version = "0.34", optional = true }

[dev-dependencies]
serde = { version = "1", features = ["derive"], default-features = true }
serde_json = "1"

[workspace]
